server:
  port: 9005
  #GZIP压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  servlet:
    context-path: /crm
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: CRM
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      #password:
      jedis:
        pool:
          #最大连接数
          max-active: 200
          #最大阻塞等待时间,负值表示不超时
          max-wait: -1
          #连接池中最大空闲连接
          max-idle: 10
          #连接池中最小空闲连接
          min-idle: 5
      #redis超时配置,单位毫秒
      timeout: 20000
